name: ComentarioIssue
on: issue_comment
jobs:
  issue_commented:    
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Comentar el problema ${{ github.event.issue.number }}"
