name: Comentario Issue
on: issue_comment
jobs:
  issue_commented    
    name: issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "comentar el problema ${{ github.event.issue.number }}"
