name: ComentarioIssue
on: issue_comment
jobs:
  issue_commented    
    name: Comentario Issue
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "comentar el problema ${{ github.event.issue.number }}"
